repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        args: [--target-version=py310]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3

  - repo: local
    hooks:
      - id: hadolint
        name: Hadolint
        entry: hadolint
        language: system
        types: [dockerfile]
        args: ["--no-fail"]

  - repo: https://github.com/ansible/ansible-lint
    rev: v6.15.0
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        entry: ansible-lint
        language: python
        types: [yaml]
        args: [--nocolor]  # Disable color output for better compatibility with CI
