version: '3.8'

services:
  melo:
    build:
      context: ./melo
      dockerfile: Dockerfile
    restart: always
    runtime: nvidia
    network_mode: host
    volumes:
      - /checkpoints/litgpt:/checkpoints

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    restart: always
    runtime: nvidia
    network_mode: host
    volumes:
      - /checkpoints/whisper:/data/models/whisper

  litgpt:
    build:
      context: ./litgpt
      dockerfile: Dockerfile
    restart: always
    runtime: nvidia
    network_mode: host
    volumes:
      - /checkpoints/litgpt:/checkpoints

  assistant:
    build:
      context: ./assistant
      dockerfile: Dockerfile
    restart: always
    runtime: nvidia
    network_mode: host
    volumes:
      - /checkpoints/litgpt:/checkpoints
    devices:
      - /dev/snd:/dev/snd
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO

networks:
  default:
    driver: bridge
